/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsoIaRouteImport } from './routes/uso-ia'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TareasPracticasRouteImport } from './routes/tareas-practicas'
import { Route as StudentLongitudinalRouteImport } from './routes/student-longitudinal'
import { Route as ProgressionRouteImport } from './routes/progression'
import { Route as MaterialesRouteImport } from './routes/materiales'
import { Route as KappaRouteImport } from './routes/kappa'
import { Route as InterraterAdminRouteImport } from './routes/interrater-admin'
import { Route as InterraterRouteImport } from './routes/interrater'
import { Route as InstrumentosCohorteRouteImport } from './routes/instrumentos-cohorte'
import { Route as ExportRouteImport } from './routes/export'
import { Route as EpisodeTimelineRouteImport } from './routes/episode-timeline'
import { Route as EpisodeNLevelRouteImport } from './routes/episode-n-level'
import { Route as EntrenamientoRecalibracionRouteImport } from './routes/entrenamiento-recalibracion'
import { Route as EjerciciosRouteImport } from './routes/ejercicios'
import { Route as CorreccionesRouteImport } from './routes/correcciones'
import { Route as CohortQuartilesRouteImport } from './routes/cohort-quartiles'
import { Route as CohortAdversarialRouteImport } from './routes/cohort-adversarial'
import { Route as IndexRouteImport } from './routes/index'

const UsoIaRoute = UsoIaRouteImport.update({
  id: '/uso-ia',
  path: '/uso-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasPracticasRoute = TareasPracticasRouteImport.update({
  id: '/tareas-practicas',
  path: '/tareas-practicas',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLongitudinalRoute = StudentLongitudinalRouteImport.update({
  id: '/student-longitudinal',
  path: '/student-longitudinal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionRoute = ProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialesRoute = MaterialesRouteImport.update({
  id: '/materiales',
  path: '/materiales',
  getParentRoute: () => rootRouteImport,
} as any)
const KappaRoute = KappaRouteImport.update({
  id: '/kappa',
  path: '/kappa',
  getParentRoute: () => rootRouteImport,
} as any)
const InterraterAdminRoute = InterraterAdminRouteImport.update({
  id: '/interrater-admin',
  path: '/interrater-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InterraterRoute = InterraterRouteImport.update({
  id: '/interrater',
  path: '/interrater',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentosCohorteRoute = InstrumentosCohorteRouteImport.update({
  id: '/instrumentos-cohorte',
  path: '/instrumentos-cohorte',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeTimelineRoute = EpisodeTimelineRouteImport.update({
  id: '/episode-timeline',
  path: '/episode-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeNLevelRoute = EpisodeNLevelRouteImport.update({
  id: '/episode-n-level',
  path: '/episode-n-level',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrenamientoRecalibracionRoute =
  EntrenamientoRecalibracionRouteImport.update({
    id: '/entrenamiento-recalibracion',
    path: '/entrenamiento-recalibracion',
    getParentRoute: () => rootRouteImport,
  } as any)
const EjerciciosRoute = EjerciciosRouteImport.update({
  id: '/ejercicios',
  path: '/ejercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const CorreccionesRoute = CorreccionesRouteImport.update({
  id: '/correcciones',
  path: '/correcciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortQuartilesRoute = CohortQuartilesRouteImport.update({
  id: '/cohort-quartiles',
  path: '/cohort-quartiles',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortAdversarialRoute = CohortAdversarialRouteImport.update({
  id: '/cohort-adversarial',
  path: '/cohort-adversarial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cohort-adversarial': typeof CohortAdversarialRoute
  '/cohort-quartiles': typeof CohortQuartilesRoute
  '/correcciones': typeof CorreccionesRoute
  '/ejercicios': typeof EjerciciosRoute
  '/entrenamiento-recalibracion': typeof EntrenamientoRecalibracionRoute
  '/episode-n-level': typeof EpisodeNLevelRoute
  '/episode-timeline': typeof EpisodeTimelineRoute
  '/export': typeof ExportRoute
  '/instrumentos-cohorte': typeof InstrumentosCohorteRoute
  '/interrater': typeof InterraterRoute
  '/interrater-admin': typeof InterraterAdminRoute
  '/kappa': typeof KappaRoute
  '/materiales': typeof MaterialesRoute
  '/progression': typeof ProgressionRoute
  '/student-longitudinal': typeof StudentLongitudinalRoute
  '/tareas-practicas': typeof TareasPracticasRoute
  '/templates': typeof TemplatesRoute
  '/unidades': typeof UnidadesRoute
  '/uso-ia': typeof UsoIaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cohort-adversarial': typeof CohortAdversarialRoute
  '/cohort-quartiles': typeof CohortQuartilesRoute
  '/correcciones': typeof CorreccionesRoute
  '/ejercicios': typeof EjerciciosRoute
  '/entrenamiento-recalibracion': typeof EntrenamientoRecalibracionRoute
  '/episode-n-level': typeof EpisodeNLevelRoute
  '/episode-timeline': typeof EpisodeTimelineRoute
  '/export': typeof ExportRoute
  '/instrumentos-cohorte': typeof InstrumentosCohorteRoute
  '/interrater': typeof InterraterRoute
  '/interrater-admin': typeof InterraterAdminRoute
  '/kappa': typeof KappaRoute
  '/materiales': typeof MaterialesRoute
  '/progression': typeof ProgressionRoute
  '/student-longitudinal': typeof StudentLongitudinalRoute
  '/tareas-practicas': typeof TareasPracticasRoute
  '/templates': typeof TemplatesRoute
  '/unidades': typeof UnidadesRoute
  '/uso-ia': typeof UsoIaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cohort-adversarial': typeof CohortAdversarialRoute
  '/cohort-quartiles': typeof CohortQuartilesRoute
  '/correcciones': typeof CorreccionesRoute
  '/ejercicios': typeof EjerciciosRoute
  '/entrenamiento-recalibracion': typeof EntrenamientoRecalibracionRoute
  '/episode-n-level': typeof EpisodeNLevelRoute
  '/episode-timeline': typeof EpisodeTimelineRoute
  '/export': typeof ExportRoute
  '/instrumentos-cohorte': typeof InstrumentosCohorteRoute
  '/interrater': typeof InterraterRoute
  '/interrater-admin': typeof InterraterAdminRoute
  '/kappa': typeof KappaRoute
  '/materiales': typeof MaterialesRoute
  '/progression': typeof ProgressionRoute
  '/student-longitudinal': typeof StudentLongitudinalRoute
  '/tareas-practicas': typeof TareasPracticasRoute
  '/templates': typeof TemplatesRoute
  '/unidades': typeof UnidadesRoute
  '/uso-ia': typeof UsoIaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cohort-adversarial'
    | '/cohort-quartiles'
    | '/correcciones'
    | '/ejercicios'
    | '/entrenamiento-recalibracion'
    | '/episode-n-level'
    | '/episode-timeline'
    | '/export'
    | '/instrumentos-cohorte'
    | '/interrater'
    | '/interrater-admin'
    | '/kappa'
    | '/materiales'
    | '/progression'
    | '/student-longitudinal'
    | '/tareas-practicas'
    | '/templates'
    | '/unidades'
    | '/uso-ia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cohort-adversarial'
    | '/cohort-quartiles'
    | '/correcciones'
    | '/ejercicios'
    | '/entrenamiento-recalibracion'
    | '/episode-n-level'
    | '/episode-timeline'
    | '/export'
    | '/instrumentos-cohorte'
    | '/interrater'
    | '/interrater-admin'
    | '/kappa'
    | '/materiales'
    | '/progression'
    | '/student-longitudinal'
    | '/tareas-practicas'
    | '/templates'
    | '/unidades'
    | '/uso-ia'
  id:
    | '__root__'
    | '/'
    | '/cohort-adversarial'
    | '/cohort-quartiles'
    | '/correcciones'
    | '/ejercicios'
    | '/entrenamiento-recalibracion'
    | '/episode-n-level'
    | '/episode-timeline'
    | '/export'
    | '/instrumentos-cohorte'
    | '/interrater'
    | '/interrater-admin'
    | '/kappa'
    | '/materiales'
    | '/progression'
    | '/student-longitudinal'
    | '/tareas-practicas'
    | '/templates'
    | '/unidades'
    | '/uso-ia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CohortAdversarialRoute: typeof CohortAdversarialRoute
  CohortQuartilesRoute: typeof CohortQuartilesRoute
  CorreccionesRoute: typeof CorreccionesRoute
  EjerciciosRoute: typeof EjerciciosRoute
  EntrenamientoRecalibracionRoute: typeof EntrenamientoRecalibracionRoute
  EpisodeNLevelRoute: typeof EpisodeNLevelRoute
  EpisodeTimelineRoute: typeof EpisodeTimelineRoute
  ExportRoute: typeof ExportRoute
  InstrumentosCohorteRoute: typeof InstrumentosCohorteRoute
  InterraterRoute: typeof InterraterRoute
  InterraterAdminRoute: typeof InterraterAdminRoute
  KappaRoute: typeof KappaRoute
  MaterialesRoute: typeof MaterialesRoute
  ProgressionRoute: typeof ProgressionRoute
  StudentLongitudinalRoute: typeof StudentLongitudinalRoute
  TareasPracticasRoute: typeof TareasPracticasRoute
  TemplatesRoute: typeof TemplatesRoute
  UnidadesRoute: typeof UnidadesRoute
  UsoIaRoute: typeof UsoIaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uso-ia': {
      id: '/uso-ia'
      path: '/uso-ia'
      fullPath: '/uso-ia'
      preLoaderRoute: typeof UsoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas-practicas': {
      id: '/tareas-practicas'
      path: '/tareas-practicas'
      fullPath: '/tareas-practicas'
      preLoaderRoute: typeof TareasPracticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-longitudinal': {
      id: '/student-longitudinal'
      path: '/student-longitudinal'
      fullPath: '/student-longitudinal'
      preLoaderRoute: typeof StudentLongitudinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progression': {
      id: '/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof ProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiales': {
      id: '/materiales'
      path: '/materiales'
      fullPath: '/materiales'
      preLoaderRoute: typeof MaterialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kappa': {
      id: '/kappa'
      path: '/kappa'
      fullPath: '/kappa'
      preLoaderRoute: typeof KappaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interrater-admin': {
      id: '/interrater-admin'
      path: '/interrater-admin'
      fullPath: '/interrater-admin'
      preLoaderRoute: typeof InterraterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interrater': {
      id: '/interrater'
      path: '/interrater'
      fullPath: '/interrater'
      preLoaderRoute: typeof InterraterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrumentos-cohorte': {
      id: '/instrumentos-cohorte'
      path: '/instrumentos-cohorte'
      fullPath: '/instrumentos-cohorte'
      preLoaderRoute: typeof InstrumentosCohorteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode-timeline': {
      id: '/episode-timeline'
      path: '/episode-timeline'
      fullPath: '/episode-timeline'
      preLoaderRoute: typeof EpisodeTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode-n-level': {
      id: '/episode-n-level'
      path: '/episode-n-level'
      fullPath: '/episode-n-level'
      preLoaderRoute: typeof EpisodeNLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrenamiento-recalibracion': {
      id: '/entrenamiento-recalibracion'
      path: '/entrenamiento-recalibracion'
      fullPath: '/entrenamiento-recalibracion'
      preLoaderRoute: typeof EntrenamientoRecalibracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ejercicios': {
      id: '/ejercicios'
      path: '/ejercicios'
      fullPath: '/ejercicios'
      preLoaderRoute: typeof EjerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correcciones': {
      id: '/correcciones'
      path: '/correcciones'
      fullPath: '/correcciones'
      preLoaderRoute: typeof CorreccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohort-quartiles': {
      id: '/cohort-quartiles'
      path: '/cohort-quartiles'
      fullPath: '/cohort-quartiles'
      preLoaderRoute: typeof CohortQuartilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohort-adversarial': {
      id: '/cohort-adversarial'
      path: '/cohort-adversarial'
      fullPath: '/cohort-adversarial'
      preLoaderRoute: typeof CohortAdversarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CohortAdversarialRoute: CohortAdversarialRoute,
  CohortQuartilesRoute: CohortQuartilesRoute,
  CorreccionesRoute: CorreccionesRoute,
  EjerciciosRoute: EjerciciosRoute,
  EntrenamientoRecalibracionRoute: EntrenamientoRecalibracionRoute,
  EpisodeNLevelRoute: EpisodeNLevelRoute,
  EpisodeTimelineRoute: EpisodeTimelineRoute,
  ExportRoute: ExportRoute,
  InstrumentosCohorteRoute: InstrumentosCohorteRoute,
  InterraterRoute: InterraterRoute,
  InterraterAdminRoute: InterraterAdminRoute,
  KappaRoute: KappaRoute,
  MaterialesRoute: MaterialesRoute,
  ProgressionRoute: ProgressionRoute,
  StudentLongitudinalRoute: StudentLongitudinalRoute,
  TareasPracticasRoute: TareasPracticasRoute,
  TemplatesRoute: TemplatesRoute,
  UnidadesRoute: UnidadesRoute,
  UsoIaRoute: UsoIaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
