"""Eventos y schemas del plano académico."""

from platform_contracts.academic.ejercicio import (
    AntiPatronSchema,
    BancoPreguntasSchema,
    CriterioRubricaSchema,
    EjercicioCreate,
    EjercicioRead,
    EjercicioUpdate,
    HeuristicaCierreSchema,
    MisconceptionSchema,
    PistaSchema,
    PreguntaSocraticaSchema,
    PrerequisitosSchema,
    RubricaEjercicioSchema,
    TestCaseSchema,
    TpEjercicioCreate,
    TpEjercicioRead,
    TpEjercicioUpdate,
    TpEjerciciosValidator,
    TutorRulesSchema,
)
from platform_contracts.academic.events import (
    CarreraCreada,
    ComisionCreada,
    EstudianteInscripto,
    MaterialIngerido,
    UniversidadCreada,
)

__all__ = [
    "AntiPatronSchema",
    "BancoPreguntasSchema",
    "CarreraCreada",
    "ComisionCreada",
    "CriterioRubricaSchema",
    "EjercicioCreate",
    "EjercicioRead",
    "EjercicioUpdate",
    "EstudianteInscripto",
    "HeuristicaCierreSchema",
    "MaterialIngerido",
    "MisconceptionSchema",
    "PistaSchema",
    "PreguntaSocraticaSchema",
    "PrerequisitosSchema",
    "RubricaEjercicioSchema",
    "TestCaseSchema",
    "TpEjercicioCreate",
    "TpEjercicioRead",
    "TpEjercicioUpdate",
    "TpEjerciciosValidator",
    "TutorRulesSchema",
    "UniversidadCreada",
]
