/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TareasPracticasRouteImport } from './routes/tareas-practicas'
import { Route as StudentLongitudinalRouteImport } from './routes/student-longitudinal'
import { Route as ProgressionRouteImport } from './routes/progression'
import { Route as MaterialesRouteImport } from './routes/materiales'
import { Route as KappaRouteImport } from './routes/kappa'
import { Route as InstrumentosCohorteRouteImport } from './routes/instrumentos-cohorte'
import { Route as ExportRouteImport } from './routes/export'
import { Route as EpisodeNLevelRouteImport } from './routes/episode-n-level'
import { Route as EjerciciosRouteImport } from './routes/ejercicios'
import { Route as CorreccionesRouteImport } from './routes/correcciones'
import { Route as CohortAdversarialRouteImport } from './routes/cohort-adversarial'
import { Route as IndexRouteImport } from './routes/index'

const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasPracticasRoute = TareasPracticasRouteImport.update({
  id: '/tareas-practicas',
  path: '/tareas-practicas',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLongitudinalRoute = StudentLongitudinalRouteImport.update({
  id: '/student-longitudinal',
  path: '/student-longitudinal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionRoute = ProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialesRoute = MaterialesRouteImport.update({
  id: '/materiales',
  path: '/materiales',
  getParentRoute: () => rootRouteImport,
} as any)
const KappaRoute = KappaRouteImport.update({
  id: '/kappa',
  path: '/kappa',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentosCohorteRoute = InstrumentosCohorteRouteImport.update({
  id: '/instrumentos-cohorte',
  path: '/instrumentos-cohorte',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeNLevelRoute = EpisodeNLevelRouteImport.update({
  id: '/episode-n-level',
  path: '/episode-n-level',
  getParentRoute: () => rootRouteImport,
} as any)
const EjerciciosRoute = EjerciciosRouteImport.update({
  id: '/ejercicios',
  path: '/ejercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const CorreccionesRoute = CorreccionesRouteImport.update({
  id: '/correcciones',
  path: '/correcciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortAdversarialRoute = CohortAdversarialRouteImport.update({
  id: '/cohort-adversarial',
  path: '/cohort-adversarial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cohort-adversarial': typeof CohortAdversarialRoute
  '/correcciones': typeof CorreccionesRoute
  '/ejercicios': typeof EjerciciosRoute
  '/episode-n-level': typeof EpisodeNLevelRoute
  '/export': typeof ExportRoute
  '/instrumentos-cohorte': typeof InstrumentosCohorteRoute
  '/kappa': typeof KappaRoute
  '/materiales': typeof MaterialesRoute
  '/progression': typeof ProgressionRoute
  '/student-longitudinal': typeof StudentLongitudinalRoute
  '/tareas-practicas': typeof TareasPracticasRoute
  '/templates': typeof TemplatesRoute
  '/unidades': typeof UnidadesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cohort-adversarial': typeof CohortAdversarialRoute
  '/correcciones': typeof CorreccionesRoute
  '/ejercicios': typeof EjerciciosRoute
  '/episode-n-level': typeof EpisodeNLevelRoute
  '/export': typeof ExportRoute
  '/instrumentos-cohorte': typeof InstrumentosCohorteRoute
  '/kappa': typeof KappaRoute
  '/materiales': typeof MaterialesRoute
  '/progression': typeof ProgressionRoute
  '/student-longitudinal': typeof StudentLongitudinalRoute
  '/tareas-practicas': typeof TareasPracticasRoute
  '/templates': typeof TemplatesRoute
  '/unidades': typeof UnidadesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cohort-adversarial': typeof CohortAdversarialRoute
  '/correcciones': typeof CorreccionesRoute
  '/ejercicios': typeof EjerciciosRoute
  '/episode-n-level': typeof EpisodeNLevelRoute
  '/export': typeof ExportRoute
  '/instrumentos-cohorte': typeof InstrumentosCohorteRoute
  '/kappa': typeof KappaRoute
  '/materiales': typeof MaterialesRoute
  '/progression': typeof ProgressionRoute
  '/student-longitudinal': typeof StudentLongitudinalRoute
  '/tareas-practicas': typeof TareasPracticasRoute
  '/templates': typeof TemplatesRoute
  '/unidades': typeof UnidadesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cohort-adversarial'
    | '/correcciones'
    | '/ejercicios'
    | '/episode-n-level'
    | '/export'
    | '/instrumentos-cohorte'
    | '/kappa'
    | '/materiales'
    | '/progression'
    | '/student-longitudinal'
    | '/tareas-practicas'
    | '/templates'
    | '/unidades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cohort-adversarial'
    | '/correcciones'
    | '/ejercicios'
    | '/episode-n-level'
    | '/export'
    | '/instrumentos-cohorte'
    | '/kappa'
    | '/materiales'
    | '/progression'
    | '/student-longitudinal'
    | '/tareas-practicas'
    | '/templates'
    | '/unidades'
  id:
    | '__root__'
    | '/'
    | '/cohort-adversarial'
    | '/correcciones'
    | '/ejercicios'
    | '/episode-n-level'
    | '/export'
    | '/instrumentos-cohorte'
    | '/kappa'
    | '/materiales'
    | '/progression'
    | '/student-longitudinal'
    | '/tareas-practicas'
    | '/templates'
    | '/unidades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CohortAdversarialRoute: typeof CohortAdversarialRoute
  CorreccionesRoute: typeof CorreccionesRoute
  EjerciciosRoute: typeof EjerciciosRoute
  EpisodeNLevelRoute: typeof EpisodeNLevelRoute
  ExportRoute: typeof ExportRoute
  InstrumentosCohorteRoute: typeof InstrumentosCohorteRoute
  KappaRoute: typeof KappaRoute
  MaterialesRoute: typeof MaterialesRoute
  ProgressionRoute: typeof ProgressionRoute
  StudentLongitudinalRoute: typeof StudentLongitudinalRoute
  TareasPracticasRoute: typeof TareasPracticasRoute
  TemplatesRoute: typeof TemplatesRoute
  UnidadesRoute: typeof UnidadesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas-practicas': {
      id: '/tareas-practicas'
      path: '/tareas-practicas'
      fullPath: '/tareas-practicas'
      preLoaderRoute: typeof TareasPracticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-longitudinal': {
      id: '/student-longitudinal'
      path: '/student-longitudinal'
      fullPath: '/student-longitudinal'
      preLoaderRoute: typeof StudentLongitudinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progression': {
      id: '/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof ProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiales': {
      id: '/materiales'
      path: '/materiales'
      fullPath: '/materiales'
      preLoaderRoute: typeof MaterialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kappa': {
      id: '/kappa'
      path: '/kappa'
      fullPath: '/kappa'
      preLoaderRoute: typeof KappaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrumentos-cohorte': {
      id: '/instrumentos-cohorte'
      path: '/instrumentos-cohorte'
      fullPath: '/instrumentos-cohorte'
      preLoaderRoute: typeof InstrumentosCohorteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode-n-level': {
      id: '/episode-n-level'
      path: '/episode-n-level'
      fullPath: '/episode-n-level'
      preLoaderRoute: typeof EpisodeNLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ejercicios': {
      id: '/ejercicios'
      path: '/ejercicios'
      fullPath: '/ejercicios'
      preLoaderRoute: typeof EjerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correcciones': {
      id: '/correcciones'
      path: '/correcciones'
      fullPath: '/correcciones'
      preLoaderRoute: typeof CorreccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohort-adversarial': {
      id: '/cohort-adversarial'
      path: '/cohort-adversarial'
      fullPath: '/cohort-adversarial'
      preLoaderRoute: typeof CohortAdversarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CohortAdversarialRoute: CohortAdversarialRoute,
  CorreccionesRoute: CorreccionesRoute,
  EjerciciosRoute: EjerciciosRoute,
  EpisodeNLevelRoute: EpisodeNLevelRoute,
  ExportRoute: ExportRoute,
  InstrumentosCohorteRoute: InstrumentosCohorteRoute,
  KappaRoute: KappaRoute,
  MaterialesRoute: MaterialesRoute,
  ProgressionRoute: ProgressionRoute,
  StudentLongitudinalRoute: StudentLongitudinalRoute,
  TareasPracticasRoute: TareasPracticasRoute,
  TemplatesRoute: TemplatesRoute,
  UnidadesRoute: UnidadesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
