"""Eventos del CTR."""

from platform_contracts.ctr.events import (
    AnotacionCreada,
    CodigoEjecutado,
    CopiaIntentada,
    CTRBaseEvent,
    EdicionCodigo,
    EpisodioAbandonado,
    EpisodioAbierto,
    EpisodioCerrado,
    IntentoAdversoDetectado,
    LecturaEnunciado,
    PegaIntentada,
    PestanaPerdida,
    PestanaRecuperada,
    PromptEnviado,
    ReflexionCompletada,
    TestsEjecutados,
    TutorRespondio,
)
from platform_contracts.ctr.hashing import (
    GENESIS_HASH,
    compute_chain_hash,
    compute_self_hash,
    verify_chain_integrity,
)

__all__ = [
    "GENESIS_HASH",
    "AnotacionCreada",
    "CTRBaseEvent",
    "CodigoEjecutado",
    "CopiaIntentada",
    "EdicionCodigo",
    "EpisodioAbandonado",
    "EpisodioAbierto",
    "EpisodioCerrado",
    "IntentoAdversoDetectado",
    "LecturaEnunciado",
    "PegaIntentada",
    "PestanaPerdida",
    "PestanaRecuperada",
    "PromptEnviado",
    "ReflexionCompletada",
    "TestsEjecutados",
    "TutorRespondio",
    "compute_chain_hash",
    "compute_self_hash",
    "verify_chain_integrity",
]
