"""Eventos y schemas del plano académico."""

from platform_contracts.academic.ejercicio import (
    DEFAULT_LANGUAGE,
    AntiPatronSchema,
    BancoPreguntasSchema,
    CriterioRubricaSchema,
    EjercicioCreate,
    EjercicioRead,
    EjercicioUpdate,
    HeuristicaCierreSchema,
    Language,
    MisconceptionSchema,
    PistaSchema,
    PreguntaSocraticaSchema,
    PrerequisitosSchema,
    RubricaEjercicioSchema,
    TestCaseSchema,
    TpEjercicioCreate,
    TpEjercicioRead,
    TpEjerciciosValidator,
    TpEjercicioUpdate,
    TutorRulesSchema,
    validar_lenguaje_unico,
    validar_tp_no_vacia,
)
from platform_contracts.academic.events import (
    CarreraCreada,
    ComisionCreada,
    EstudianteInscripto,
    MaterialIngerido,
    UniversidadCreada,
)

__all__ = [
    "DEFAULT_LANGUAGE",
    "AntiPatronSchema",
    "BancoPreguntasSchema",
    "CarreraCreada",
    "ComisionCreada",
    "CriterioRubricaSchema",
    "EjercicioCreate",
    "EjercicioRead",
    "EjercicioUpdate",
    "EstudianteInscripto",
    "HeuristicaCierreSchema",
    "Language",
    "MaterialIngerido",
    "MisconceptionSchema",
    "PistaSchema",
    "PreguntaSocraticaSchema",
    "PrerequisitosSchema",
    "RubricaEjercicioSchema",
    "TestCaseSchema",
    "TpEjercicioCreate",
    "TpEjercicioRead",
    "TpEjercicioUpdate",
    "TpEjerciciosValidator",
    "TutorRulesSchema",
    "UniversidadCreada",
    "validar_lenguaje_unico",
    "validar_tp_no_vacia",
]
